django_data_stat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from django_data_stat import settings
from user_extend.forms import AuthenticationNewForm, PasswordChangeNewForm, PasswordResetNewForm

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', views.LoginView.as_view(form_class=AuthenticationNewForm), name='login'),
    path('password_change', views.PasswordChangeView.as_view(form_class=PasswordChangeNewForm), name='password_change'),
    path('password_reset', views.PasswordResetView.as_view(form_class=PasswordResetNewForm), name='password_reset'),
    path('', include('django.contrib.auth.urls')),

    path('celery-progress/', include('celery_progress.urls')),

    path('', include('home.urls')),
    path('', include('user_extend.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name='home-page'),
    path("create_scrapping_params/", views.ScrapParamsCreateView.as_view(), name='create-scrapping-params'),
    path("list_of_ice_items/", views.ScrappedListView.as_view(), name='list-of-ice-items'),
]

home/models.py
import logging
import sys
from datetime import datetime, timedelta
from typing import Type

from django.db import models
from django.db.models import Count, fields, ExpressionWrapper, F, Func
from django.utils.timezone import now
from sqlalchemy import exists

logger = logging.getLogger(__name__)


class IceItem(models.Model):
    SOLD, AVAILABLE = 'sold', 'available'
    SOLD_OPTIONS = [(SOLD, 'SOLD'), (AVAILABLE, 'AVAILABLE')]

    title = models.TextField(max_length=100)
    brand = models.TextField(max_length=100)
    model = models.TextField(max_length=100)
    ice_type = models.TextField(max_length=100)
    price = models.DecimalField(db_index=True, max_digits=15, decimal_places=2)
    avg_price = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    url = models.URLField(db_index=True, max_length=200)
    year = models.TextField(max_length=30)
    km = models.TextField(max_length=30, null=True, default="-")
    location = models.TextField(max_length=100)
    added_date = models.TextField(max_length=30)
    sold_date = models.TextField(max_length=30)
    sold_status = models.CharField(max_length=9, null=True, choices=SOLD_OPTIONS)
    created_at = models.DateField(db_index=True, auto_now_add=True, null=True)
    updated_at = models.DateField(db_index=True, auto_now=True, null=True)

    def __str__(self):
        return f'{self.brand} {self.model} {self.price}'

    @classmethod
    def remove_sold_items(cls):
        today = datetime.now().date()
        five_days_ago = today - timedelta(days=5)
        print(f"start removing sold items {datetime.now()}")
        url_counts = cls.objects.values('url').annotate(count=Count('id'))
        for url_count in url_counts:
            if url_count['count'] > 1:
                recent_times = cls.objects.filter(url=url_count['url'], updated_at__gte=five_days_ago)
                if not recent_times.exists():
                    cls.objects.filter(url=url_count['url']).delete()
            else:
                item = cls.objects.get(url=url_count['url'])
                if item.updated_at < five_days_ago:
                    item.delete()
        print(f"removed sold items {datetime.now()}")

    @classmethod
    def update_sold_status(cls):
        print("UPDATING sold status")
        yesterday = datetime.now().date() - timedelta(days=2)
        items = cls.objects.all()

        sold_items = []
        available_items = []

        for i in items:
            if i.updated_at <= yesterday:
                i.sold_date = i.updated_at
                i.sold_status = cls.SOLD
                sold_items.append(i)
            else:
                i.sold_status = cls.AVAILABLE
                available_items.append(i)

        for chunk in [sold_items[i:i + 500] for i in range(0, len(sold_items), 500)]:
            cls.objects.bulk_update(chunk, ['sold_status', 'sold_date'])

        for chunk in [available_items[i:i + 500] for i in range(0, len(available_items), 500)]:
            cls.objects.bulk_update(chunk, ['sold_status'])


class Image(models.Model):
    image_url = models.TextField(max_length=100)
    ice_item = models.ForeignKey(IceItem, on_delete=models.CASCADE, null=True)


class ScrapParams(models.Model):
    start_price = models.DecimalField(max_digits=10, decimal_places=0, default=2000)
    year = models.IntegerField(default=2000)
    engine_size = models.IntegerField(default=250)


class Statistic(models.Model):
    title = models.DateField(auto_now_add=True)
    ice_items = models.ManyToManyField(IceItem)

    time_price_variance = models.JSONField(blank=True, null=True)

    def update_time_price_variance(self, filtered_ice_items=None):
        if filtered_ice_items:
            group_ice_items = filtered_ice_items.values('brand', 'model', 'year', 'url', 'avg_price', 'updated_at')
        else:
            group_ice_items = self.ice_items.values('brand', 'model', 'year', 'url', 'avg_price', 'updated_at')
        try:
            time_price_variance = [{
                'brand': item['brand'],
                'model': item['model'],
                'year': item['year'],
                'time': item['updated_at'].strftime("%Y-%m-%d"),
                'avg_price': float(item['avg_price'])
            } for item in group_ice_items]
            self.time_price_variance = time_price_variance
        except TypeError:
            tb = sys.exc_info()[0]
            print(f'update_time_price_variance exception: {tb}')

    def update_statistic(self):
        self.update_time_price_variance()
        self.save()
        # delete all entries except the last one
        Statistic.objects.exclude(id=self.id).delete()


class DaysAvailableExpression(models.Expression):
    def __init__(self, **extra):
        super().__init__(output_field=fields.IntegerField(), **extra)

    def as_sql(self, compiler, connection):
        return """
            (EXTRACT(EPOCH FROM updated_at) - EXTRACT(EPOCH FROM created_at)) / 86400 + 1
        """, []

templates/scrapping/create_scrapping_params.html
{% extends 'base.html' %}

{% block title %}Select Details{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="col-md-6 offset-md-3 py-3">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Update scrapping params</h3>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-outline-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/scrapping/custom_price_avg_btn_group.html
<div class="row d-flex align-items-center p-3">
    <h5 class="d-flex aligned">Price</h5>
    <div class="col-auto d-flex align-items-center px-3">
        <div class="btn-group col-md4" role="group" aria-label="Basic mixed styles example">
            <form action="" method="get">
                <input type="hidden" name="price_avg" value="HIGH">
                {% for key, value in filter_params_preserved.items %}
                    {% if key != "price_avg" %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-danger">High</button>

            </form>
            <form action="" method="get">
                <input type="hidden" name="price_avg" value="AVERAGE">
                {% for key, value in filter_params_preserved.items %}
                    {% if key != "price_avg" %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-warning">Average</button>
            </form>
            <form action="" method="get">
                <input type="hidden" name="price_avg" value="LOW">
                {% for key, value in filter_params_preserved.items %}
                    {% if key != "price_avg" %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-success">Low</button>
            </form>
            <form action="" method="get">
                <input type="hidden" name="price_avg" value="NO_REFERENCE">
                {% for key, value in filter_params_preserved.items %}
                    {% if key != "price_avg" %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-secondary">No reference</button>
            </form>
        </div>
    </div>
</div>

templates/scrapping/ice_item_card.html
{% now "Y-m-d" as current_date %}
<div class="card d-flex h-80" style="cursor: pointer">
    {% if i.avg_price %}
        {% if i.price < i.avg_low %}
            <div class="card-header bg-success"></div>
        {% elif i.avg_price == i.price %}
            <div class="card-header bg-secondary"></div>
        {% elif i.price > i.avg_high %}
            <div class="card-header bg-danger"></div>
        {% elif i.avg_low < i.price and i.avg_high > i.price %}
            <div class="card-header bg-warning"></div>
        {% endif %}
    {% else %}
        <div class="card-header bg-secondary"></div>
    {% endif %}
    <div class="card-header">
        <h5 class="card-title text-center"> {{ i.brand | title }} {{ i.model | upper }}</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <p class="card-text">
                    <i class="bi bi-geo-alt"></i>
                    {{ i.location }}
                </p>
            </div>
             <div class="col-4">
                <p class="card-text">
                    <i class="bi bi-calendar3"></i>
                    {{ i.year }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <p class="card-text">
                    <i class="bi bi-calendar-plus"></i>
                    {{ i.added_date }}
                </p>
            </div>
            <div class="col-4">
                <p class="card-text">
                    <i class="bi bi-cash"></i>
                    {{ i.price|floatformat:'0' }} &euro;
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <p class="card-text">
                    <i class="bi bi-map"></i>
                    {{ i.km }}
                </p>
            </div>
            <div class="col-4 ms-auto">
                <p class="card-text">
                    <i class="bi bi-calculator"></i>
                    {{ i.avg_price|floatformat:'0' }} &euro;
                </p>
            </div>
        </div>
        <div class="row mt-2">
            {% if i.image_set.exists %}
                <div id="carouselExampleIndicators{{ i.id }}" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        {% for image in i.image_set.all %}
                            <button type="button" data-bs-target="#carouselExampleIndicators{{ i.id }}"
                                    data-bs-slide-to="{{ forloop.counter0 }}"
                                    class="{% if forloop.first %}active{% endif %}" aria-current="true"
                                    aria-label="Slide {{ forloop.counter }}"></button>
                        {% endfor %}

                    </div>
                    <div class="carousel-inner">
                        {% for image in i.image_set.all %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <img src="{{ image.image_url }}" class="d-block w-100"
                                     style="height: 200px; object-fit: cover"
                                     alt="Picture {{ forloop.counter }}">
                            </div>
                        {% endfor %}

                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators{{ i.id }}"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators{{ i.id }}"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            {% else %}
                <img class="img-fluid" src="/no_image_available.png" alt="Image missing">
            {% endif %}
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center align-items-center
        {% if i.sold_status == 'sold' %}
            text-danger
        {% else %}
            text-success
        {% endif %}"
         style="color:white; height: 30px"
         onclick="location.href='{{ i.url }}';">

        {% if i.sold_status == 'available' %}
            Available ({{ i.days_available }} days)
        {% else %}
            Sold (in {{ i.days_available }} days)
        {% endif %}
    </div>
</div>

templates/scrapping/list_of_ice_items.html
{% extends 'base.html' %}

{% block title %}List of ICE{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row ">
            {% include 'scrapping/scrapped_data_filter.html' with reset_url='list-of-ice-items' %}
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-10">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9">
                        {% include 'scrapping/custom_price_avg_btn_group.html' %}
                    </div>
                    <div class="d-none d-xs-block d-md-block col-md-4 col-lg-3 d-flex align-items-center justify-content-end">
                        {% include 'custom_pagination.html' %}
                    </div>
                </div>
                {% if page_obj %}
                    <div class="grid">
                        {% for i in page_obj %}
                            <div class="grid-item g-3">
                                {% include 'scrapping/ice_item_card.html' %}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <h2 class="col-md-6 offset-md-3 bg-primary-subtle text-center p-3">No items</h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/scrapping/scrapped_data_filter.html
<div class="d-none d-md-block col-md-4 col-lg-3 col-xl-2 gy-3">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center">Filters</h2>
        </div>
        <form method="get">
            <div class="card-body">
                {{ form_filters.as_p }}
            </div>
            <div class="card-footer text-center">
                <button type="submit" class="btn btn-outline-success m-3">Apply filters</button>
                <a href="{% url reset_url %}" class="btn btn-outline-danger">Reset</a>
            </div>
        </form>
    </div>
</div>